init: initial configurations
dscnitrourkela/project-kiwi pull request #2
Opened 2021-09-03 14:46 UTC by sambit-sankalp

2021-09-03 21:30 UTC, nayakastha requested changes

2021-09-03 21:30 UTC, nayakastha commented on CONTRIBUTING.md
> +$ git remote add upstream https://github.com/dscnitrourkela/<Repo-Name>.git
add correct repo name instead of <repo-name>

2021-09-04 17:13 UTC, nayakastha approved these changes

2021-09-06 04:05 UTC, riteshsp2000 approved these changes

2021-09-06 04:07 UTC, riteshsp2000 commented
Hey @sambit-sankalp You haven't added the following
- Github issues template
- Github PR template
- Github action for codeql-analysis

2021-09-11 11:53 UTC, CIPHERTron commented
Heyy @sambit-sankalp have you made sure that ES Lint and Prettier are working correctly?

2021-09-11 12:50 UTC, CIPHERTron commented
> Heyy @sambit-sankalp have you made sure that ES Lint and Prettier are working correctly?

nvm

2021-09-11 12:50 UTC, CIPHERTron approved these changes

2021-09-11 12:52 UTC, merged